### ISSUE TITLE
Improve the UX for missing mandatory fields in all forms

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1065]
The look and feel of the listed fields when missing mandatory details at the time of creation of a new device can be improved (see image attached). 

I'd suggest
.- highlighting the areas to which users should pay attention, to save them time and the effort of comparing the names of the fields and the fields listed at the top
.- ordering the listed fields following the order in which they appear on the form, so it's intuitive and saves time for users if they need to double-check if they have covered it all

![Screen Shot 2021-03-18 at 10 47 49 AM](https://user-images.githubusercontent.com/2902379/111609027-29de8000-87da-11eb-8b5b-98b36bbeac2e.png)

![Screen Shot 2021-03-18 at 10 34 09 AM](https://user-images.githubusercontent.com/2902379/111606060-21d11100-87d7-11eb-92a3-3f2e9670edac.png)

**Comment by straight-shoota** [comment]
Ideally, error messages should be attached directly to the form fields they apply to. In my experience, that's a good and well established practice.

It is a great improvement to visually highlight fields with errors. Some form fields are already highlighted with red foreground color, but that's not applied everywhere.

**Comment by straight-shoota** [comment]
This blog post describes a helper for grouping form fields consisting of label, the actual input field and error message. I think this can adapt to our form structure as well. With a few customizations of course.

https://qiita.com/alokrawat050/items/dc7f4a7ee1acdc6a449a

**Comment by straight-shoota** [comment]
Adding the fields error helper for just a couple of fields as in the first iteration of https://github.com/instedd/cdx/pull/1623 is definitely insufficient. Technically, *every* field can have errors. That means *every* field needs a way to display those errors.

I would consider going for a `form_group_for` helper as suggested in the previous comment.
This simply abstracts the common pattern of a label, field and errors into a reusable piece. It would be applied to *every* field, except for some special cases which need some customization. But I'm pretty sure it should fit for the vast majority of fields.

**Comment by straight-shoota** [comment]
Alternatively, we could also consider using a form builder like [simple_form](https://github.com/heartcombo/simple_form) which already includes support for error messages (and hints btw.). It also allows defining custom components for abstracting the boilerplate form structure (like the rows and cols).

**Comment by straight-shoota** [comment]
@jkicillof I couldn't find any designs for error messages in normal forms, only in the login-help form you mentioned in https://github.com/instedd/cdx/pull/1623#issuecomment-1126073082. But that has a different style.
I don't think going all caps on error messages would be a good idea.

The screen shot in #1662 shows what I implemented.

**Comment by jkicillof** [comment]
Ok, let's got with sentence case errors. Why is there so much space between the label and the input?

**Comment by jkicillof** [comment]
I still have to design the top error message

**Comment by straight-shoota** [comment]
> Why is there so much space between the label and the input?

Apparently, the original forms use different widths for the label columns. Some examples:

* sites: `.col.pe-2`
* batches: `.col.pe-3`
* samples: `.col.pe-4`
* institution: `.col.px-1`

I'm pretty sure that's not always fully intended but just a result of boilerplate copy pasta.

I have standardized this and used the biggest one `pe-4`. It can certainly be narrowed down. And we can still have custom overrides when necessary, but most forms actually should be pretty similar with regards to the space requirements for form labels.

A reason for different widths might be that the samples form has space on the right side for the label preview. That probably results in the bigger width class because the sizes are relative and when that form misses 40% of the width, doubling the width of the column results in a roughly equivalent label width than other forms.
I believe an absolute width would be more appropriate here. That would make the width of the labels independent of available space for the entire form and result in a more consistent layout.
The grid system comes with `px-*` classes for this (which are absolute width instead of the relative width of `pe-*`), but `px-2` is too narrow and `px-3` a bit too wide. So I'm going to use a custom width here.

This is the updated view with fixed width of `17em`:

![grafik](https://user-images.githubusercontent.com/466378/168759383-eb7046cb-0fcc-4445-9691-0a9e1e5324df.png)

**Comment by jkicillof** [comment]
This look much better! thanks

**Comment by jkicillof** [comment]
Here's the [screen with errors](https://invis.io/Z7OD63XAWKF#/467087061_New_Sample_-_Erros). There's a general message on top that could have a list if needed.

**Comment by mmuller** [comment]
> .- highlighting the areas to which users should pay attention, to save them time and the effort of comparing the names of the fields and the fields listed at the top
> .- ordering the listed fields following the order in which they appear on the form, so it's intuitive and saves time for users if they need to double-check if they have covered it all

According to the original report or suggestion, it seems like this issue is not fixed yet in version 3f8fdea

Device:
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/518152/169901846-f13b1b2c-3cf2-4c37-bdca-0cd430aff3ac.png">
 
Role:
<img width="754" alt="image" src="https://user-images.githubusercontent.com/518152/169901929-70a58fca-2e87-46a2-9a4c-89bfb7e66f8e.png">

Batch:
<img width="977" alt="image" src="https://user-images.githubusercontent.com/518152/169902088-6ff6265d-5037-49ee-89cd-5480c9b212f5.png">

**Comment by straight-shoota** [comment]
https://github.com/instedd/cdx/pull/1662 only provided the mechanism and adopted it for some forms. We still need to port the rest of the forms to use the new mechanism. I have started with some of them and make a PR shortly.
