### ISSUE TITLE
Invites - Create data flow diagram

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1355]
Where will the invitation data be stored? What happens with invitations that are never accepted?  Will there be a status? What happens when the invitation is accepted?

**Comment by ysbaddaden** [comment]
@gbatiston @ftarulla @devduarte Shall we take some time to design this?

I don't know how user invites to an institution are done, maybe we could use the same structure?

From the top of my mind, I'd introduce a new table (e.g. `pending_institution_invites` or a generic `pending_invites`) to store the prefill data + user information, with an unique token, so we can retrieve the record when the user clicks on the invite link. The record may be deleted after the institution is created.

It avoids to impede the list of institutions with pending data, we can list pending invitations, and we may be able to warn that an invite is already pending for user X or institution Y, avoiding duplicates.

> What happens with invitations that are never accepted?

From a technical point of view, there should be a time limit (e.g. one month). I'd have a single status: pending or expired; I'd delete the invitation when the institution is created.

From a user point of view, we could list pending invitations, have a button to send the invitation again —useful if it expired or has been lost in spam hell. There could even be a cancel button.

We'll need more input from @gbatiston for further design.

**Comment by diegoliberman** [comment]
> From a user point of view, we could list pending invitations

Actually, I asked about this and for this first stage, we don't need to provide an UI for seeing pending invitations.  I also think it's a good feature, but let's see what's the project status once we complete a basic invitation flow.

PS: Ger is on vacation this week.  I'd move forward with this task without Ger.  We can receive the feedback later and iterate if needed.

**Comment by gbatiston** [comment]
Does this need any more input on my end?

**Comment by diegoliberman** [comment]
> Does this need any more input on my end?

Not for now.

**Comment by devduarte** [comment]
# Technical Information


## Process Overview
![Screen Shot 2021-12-01 at 10 36 52](https://user-images.githubusercontent.com/23437283/144244070-addb9bc5-3cae-401d-9e6c-c7505f8e067a.png)

## Current Users invitation process
![Screen Shot 2021-12-01 at 10 38 28](https://user-images.githubusercontent.com/23437283/144244307-06ec37ee-e45c-45b8-bf88-32f93a7bc8ec.png)

## Institution invitation process DFD 
![Screen Shot 2021-12-01 at 10 39 20](https://user-images.githubusercontent.com/23437283/144244417-098170b7-b529-4e6b-8693-11c8bfb4a118.png)


Link to whole Diagram

https://drive.google.com/file/d/1uouAU9ysR9LosQYSUZOTCnRjHHyViguu/view?usp=sharing

## New process steps and helpful information
- We should create a new endpoint (users_controller.rb or maybe a new pending_invitations_controller.rb) to send the new Institution's data along with the superadmin User in charge.
- Then we create the unconfirmed user, save the institution data and finally send the invite to the new User. Current process of User's invitation is being handled here in the `craete` method of `users_controller.rb`, so we probable will reuse a lot of that code.
-We can store the token being used by the user, but probably using the `user_id` as a FK seems to be enough. Devise manages an `invitation_token` and a `confirmation_token`. The one we really care about is the `confirmation_token` as users may accept an invite, but don't confirm its status. If we need to do something at confirmation time, we would have to override Devise's `confirm` method on `users_controller.rb`
- SessionsController has a `skip_before_action :check_no_institution!, only: :destroy` which checks all the necessary conditions if a user does not have an Insitution assigned or even if there is no Institution at all. This method is defined in `application_controller` and also checks the conditions of when the user has to create an Institution and redirects it to a `new_institution_path`. 
- Instead of redirecting to a `new_institution_path` we should trigger the `create` method of the `institutions_controller.rb` with the data saved in `pending_institutions_invites` as params to finally create the Institution and then redirect to the `root_path`.

**Comment by ysbaddaden** [comment]
That looks good.

We should reuse the regular user invitation process, and add the ability to specify data for the institution to both the form and the `users#create` action, with a parameter to show/hide the form (invite user => no institution form, invite user to start an institution => show form).

> Instead of redirecting to a new_institution_path we should trigger the create method of the institutions_controller.rb

:+1: we can add an action (e.g. `institutions#pending`) that will load the pending data then render the `new` template with it.
