### ISSUE TITLE
[BUG] Files attached to QC seems to have disappeared during latest PROD rollouts

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1427]
### Bug Details
 This bug has been raised by the RADx Lab team. They mention having noticed that some QC that previously had files and test results attached, seem to have these files missing after one of the latest Prod updates. 

They have shared this Sample ID (B.1.1.7 (279ce019-3f57-0fe2-1301-880aff8c28be)) as an example of this situation. They have been re-attaching lost files, recently, but I hope we can identify if something from our side could have caused this.

**Comment by devduarte** [comment]
@gbatiston can you provide us more Samples examples/cases of this issue happening?
Looking at DB backups, there were no AssayAttachment losses between the day before and after the deploy that contained a migration regarding AssayAttachments, (January 18th, v0.17.2). Between December 2nd and January 17th there were 3 new AssaysAttachments and none of them (including the older ones in the table) belongs to this Sample (279ce019-3f57-0fe2-1301-880aff8c28be).
The Sample was created on November 2021 and we don't have any backups from that month, so what could have happened is that the problem happened on November and they just noticed it in January.

cc: @diegoliberman

**Comment by gbatiston** [comment]
@devduarte here's some more info Alex shared on the matter: 

> Correction to the missing file issue: the sample id is 45a884dd-d138-43e1-d87e-2d43dc4f9195. This sample is also a Q file not showing up when filtering by Q sample role.
> 
> It had files uploaded between Nov 2nd and 4th. [...] It has 2 empty assay files, and there were supposed to be 2 files with it.

Let me know if this info helps, or if you have more questions

**Comment by devduarte** [comment]
@gbatiston @diegoliberman 
Update: we researched again with the data that Ger provided and found that we actually did lose files references. This happened in November's deploy which had the first version of migrating the AssayAttachment files to AssayFiles model (20211104135226_migrate_assay_attachment_pictures_to_assay_file). 
Good news is that this is fixeable and we already know how to do it: we have the files stored in S3 and the AssayAttachments Ids that they belonged to. We don't have the filenames, since they got hashed by Paperclip (a library that we use), so we should ask the UCSD team if this is important for the. If it is, we will need them to provide the filenames.
Mati offer himself to do it, since he has the prod access, but I can help him with the rest of the job. I think that the fix shouldn't take a lot of time, a few hours will work (Mati, correct me if I'm wrong here 

From the development side we need to reproduce this again (checkouting back to the version that caused this issue) to check what happened since there are multiple possible escenarios that could have caused it. The strongest theory is that we missed to use Paperclip for migrating the files from one model to another. Whatever the confirmed root cause is, we will need to fix the migration file. I'm creating an issue and let you guys decide the priority.

cc: @matiasgarciaisaia

**Comment by devduarte** [comment]
[issue](https://github.com/instedd/cdx/issues/1461) created.

**Comment by gbatiston** [comment]
@devduarte I have asked Alex if file names are relevant for them. As soon as we have an answer I'll let you guys know.

**Comment by matiasgarciaisaia** [comment]
We got confirmation today that the filenames are not important.
