### ISSUE TITLE
Attachments fail to appear after saving the Sample in Staging

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1464]
1. Create a new Sample
2. Enter a Production Date
3. Create an Assay with a Loinc Code, Result and Attachment
4. Save the Sample
5. Open the sample again.  The attachment link will be missing.

![image](https://user-images.githubusercontent.com/25181052/154256677-340943cb-34a8-4597-a540-d3c8722fe7b7.png)

**Comment by ysbaddaden** [comment]
But I reproduce immediately in staging!

**Comment by ysbaddaden** [comment]
Looking at the logs: the assay file has been created in the background, but when I created the sample, it only saved the loinc code and result, and didn't link the previously uploaded assay file.

Oh, the server replies with a 200 OK, and I do see an `INSERT INTO assay_files` followed by a `COMMIT` SQL queries in the logs, _but_ the response body is `{"status": "error"}`, so it actually failed for some reason!

I identify a few problems:

1. the UI doesn't report upload errors, and looks like everything is fine;
2. the `assay_files#create` action silences errors, so they aren't logged, and it's silenced inside the transaction, so it COMMIT instead of ROLLBACK. See #1474

I suppose there is an error when saving the file to the storage or with Paperclip that only happens in staging, but we'll have to push #1474 to know more.

**Comment by diegoliberman** [comment]
The issue didn't happen anymore after Staging was started.
