### ISSUE TITLE
Investigate slow spec suite run time

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/cdx#1502]
We must investigate why the CDx spec suite is so slow.

Just the unit tests are taking 6 to 7 minutes to run, without accounting for the integration specs which add another 3 to 4 minutes to the overall test run, but integration are slow by design, since they involve interacting with a real browser, loading pages, executing requests, and so on.

**Comment by straight-shoota** [comment]
Callbacks and policies look like a good candidate. Especially if they involve multiple database round trips. I've noticed that in the dev server logs. I believe most of that shouldn't be necessary for the majority of unit tests. Maybe we can find a way to reduce that.

Creating objects for unit tests should be simple and efficient. If we can achieve that, there's no need for global fixtures. I don't like them because it's hard to keep track of the global state.

Upgrading Ruby (and Rails for that matter) should certainly improve performance. Most likely not by much. But maybe we're hitting something that has been improved a lot in recent versions :shrug:

Migrating some controller specs to model specs could also help to some extent. For example, I noticed in `batches_controller_spec` that there are many specs testing for all kinds of validation errors. They should rather be model specs instead. The controller specs only need to ensure the behaviour when validation fails, but there's no need to go through all the different conditions for that (when it's already covered on the model).

**Comment by straight-shoota** [comment]
Is this really resolved? I believe the specs are still running quite slowly.

In fact, I just compared performance before and after the latest spec-related changes, and it's almost identical:

d3650ee98e9892e779a7d0285640c744137ae419
```
Finished in 10 minutes 3 seconds (files took 6.53 seconds to load)
1375 examples, 0 failures, 9 pending

Randomized with seed 8144

real    10m10.489s
user    7m40.087s
sys     0m28.359s
```

9bd81d421a749b5934ad854a760e098a3797a90c

```
Finished in 10 minutes 3 seconds (files took 6.67 seconds to load)
1375 examples, 0 failures, 9 pending

Randomized with seed 50387

real    10m10.005s
user    7m7.719s
sys     0m29.322s
```

I was already questioning whether I had inadvertently run it on the same commit, but there was a difference regarding `TestRail` output, so it was not the same 😅

**Comment by ysbaddaden** [comment]
:sob: Let me run the specs at the different steps, and see if I get any benefit.

**Comment by ysbaddaden** [comment]
It works on my machine :face_in_clouds: 

- Before (d3650ee98e9892e779a7d0285640c744137ae419):
  Finished in 7 minutes 48 seconds (files took 1.49 seconds to load)
- Now (ca673054fc96fcd8a37d03cb2a95b27858725f25):
  Finished in 6 minutes 6 seconds (files took 1.16 seconds to load)

I simply ran `bin/rspec` inside a fresh `docker-compose run --rm web bash` shell.

But I have this override in my `docker-compose.override.yml` to speedup MySQL, but I doubt it has such an impact:

```yaml
version: '2.0'

services:
  db:
    command: --innodb-flush-method=nosync --innodb-flush-log-at-trx-commit=0 --innodb-flush-log-at-timeout=2700 --sync-binlog=0
```

But if it does, then we should add this to the main `docker-compose.yml`!

**Comment by straight-shoota** [comment]
I tried with that override command, an now I also see a reasonable improvement: 7:32 min vs 10:50 min
It's still not *fast* though. But I suppose it's good for now. Maybe we can come revisit after the upgrade sequence is completed.

**Comment by straight-shoota** [comment]
And it seems we should really add the override to the main config. I have no idea how that makes it faster, though.
