### ISSUE TITLE
Fasta files can't be downloaded from Production

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1503]
### Steps to reproduce the issue
1. Using Google Chrome, create a Sample
2. Add an Assay
3. Attach a fasta file
4. Save the Assay
5. Go back to the Sample
6. Try to download the fasta file by clicking on the link

Result: a new tab is opened and closed in 1 second, no download prompt appears.

7. Try to download the file by using the "Save link as" option from the contextual menu.  You'll get the following error message: "<filename> can't be downloaded securely".

<img width="340" alt="image" src="https://user-images.githubusercontent.com/25181052/156633770-f46be7ab-070f-49ef-8f00-08b58d43135e.png">

PS 1: It works fine with Firefox.
PS 2: It works fine in Staging.

Quick googling points to [this](https://www.technipages.com/chrome-this-file-cant-be-downloaded-securely)

[Fasta File and Screen Recording](https://drive.google.com/drive/folders/1cVQerRXbS4TLpl1cDBRIiGXm0c2Oh7g5)

**Comment by matiasgarciaisaia** [comment]
The link to download files is a (plain, insecure) HTTP link to S3 (instead of using HTTPs).

I guess that would be the cause - visitor is on a secure page that makes them download a file from a non-secure site. Maybe it works with other files due to more common formats/extensions (ie, Chrome decided an untrusted JPG is harmless, but not a fasta file). And I guess we don't have that issue in staging because we don't use paperclip there - so we serve the files from Rails itself instead of from S3.

So we should check if there's a way to ask Paperclip for an S3 HTTPs URL, probably. Or something like that.

**Comment by ysbaddaden** [comment]
Found in the documentation of [Paperclip 4.3.6](https://www.rubydoc.info/gems/paperclip/4.3.6/Paperclip/Storage/S3):

> `s3_protocol`: The protocol for the URLs generated to your S3 assets. Can be either 'http', 'https', or an empty string to generate protocol-relative URLs. Defaults to 'http' when your :s3_permissions are :public_read (the default), and 'https' when your :s3_permissions are anything else.
