### ISSUE TITLE
Form fields are slightly offset

### ISSUE THREAD

**Issue by straight-shoota** [instedd/cdx#1509]
Baseline (vertical alignment):

![grafik](https://user-images.githubusercontent.com/466378/157044643-72acaca2-c00c-4a22-b4d8-c14bd07bfba1.png)

I think the vertical alignment is off on all fields.

Horizontal alignment:
![grafik](https://user-images.githubusercontent.com/466378/157044487-2b176ebb-73a7-4a90-93c9-113b2324d64a.png)

This applies only to some fields. As you can see, the CdxSelect box is horizontally aligned with the UUID (which is not in a form field).

**Comment by leandroradusky** [comment]
Here I think is better if I ask since don't dare to apply my criteria and moving forward:

![image](https://user-images.githubusercontent.com/13782680/158225314-08b3da1e-457e-4a2b-b902-4387996db092.png)

Here the fields on the form are highlighted in blue (as happens when you input a value) and we can see the "boxes" containing them.

Respect to the horizontal alignment is quite clear that the text should start in the same pixel for all the types of fields. But respect to the vertical, I should make the blue boxes smaller in order to accomodate the text at the same level? or I should keep the box size and displace it down to have the text at the same level?

**Comment by diegoliberman** [comment]
I guess that the Input element should have the same height that the label, and both should align its content vertically in the middle.  

I see that the label has a height of 40px, whereas the input is 30px.  I guess this could be fixed by increasing the inputs' height to 40px.  

![image](https://user-images.githubusercontent.com/25181052/158240156-43e06374-87c3-45cd-b369-e31019aed398.png)
![image](https://user-images.githubusercontent.com/25181052/158240235-dbcb4f11-46d4-4078-83c0-66a348832a5b.png)

I think the result is better by reducing the label height to 30px:
![image](https://user-images.githubusercontent.com/25181052/158240689-8a8f7f84-af45-483a-b4d2-17493f6a5fc0.png)
![image](https://user-images.githubusercontent.com/25181052/158240725-b9a569e6-5536-4add-82c6-bf90f0819adc.png)

Because when assigning a height of 40px to the input, the bottom border line gets too far away from the actual input's text.

The [design](https://projects.invisionapp.com/d/main#/console/4103589/113463974/preview) might help.

**Comment by straight-shoota** [comment]
The total height of the individual elements actually doesn't matter that much for this. It's the line height that counts, as well as the paddings (and margins).

Then I think the easiest solution is to apply the same line height and paddings to all form fields and values that are displayed but not actual fields (such as the UUID).
