### ISSUE TITLE
Sample ID should not get obfuscated for the sender

### ISSUE THREAD

**Issue by gbatiston** [instedd/cdx#1526]
### Details
When an institution sends samples to a recipient, the sample ID for the sender in the transfer section gets the last 4 digits obfuscated, but that shouldn't be the case, as the sender knows which samples have been sent. Obfuscating the sampleID is a security device implemented for recipients to confirm they received the right samples. 

### Steps to reproduce
1. Send a sample from institution A to Institution B
2. From the sender profile, navigate to the Transfer menu

Expected: the transferred sample's sample id is fully visible for the sender
Actual: the transferred sample's sample ID gets the last 4 digits obfuscated

**Comment by diegoliberman** [comment]
Verified in `Version: dev-525a860 (build 1058)`. I was able to verified this only by reducing the browser's font size.  So that the entire UUID would fit.   

![image](https://user-images.githubusercontent.com/25181052/158252118-32c31a63-1207-48f5-bdb8-ed3625202cb8.png)
![image](https://user-images.githubusercontent.com/25181052/158252203-06a01617-5cc3-4f49-9b0d-adb6c79fa48f.png)
