### ISSUE TITLE
The transfer action should be showing a success message

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1528]
As described in the [design](https://projects.invisionapp.com/d/main#/console/4103589/461729949/preview), after transferring samples, we should be showing a success toast message.

**Comment by straight-shoota** [comment]
I'm going to add some details on what I mentioned in https://github.com/instedd/cdx/pull/1559#issuecomment-1078205377 here, because they're relevant for fixing this bug.

We don't need any fancy client side scripts to get this working correctly (enhance the visuals with the snackbar is nice, of course, but that's not essential behaviour). Having an action show a notification is a basic Rails feature. The reason why it doesn't work here is because we're using it wrong. We have some fancy client side script that completely disregards how Rails' HTTP API is supposed to be used. Doing this caused the error in the first place. We shouldn't pile more fancy scripts on top to mitigate the effects and instead fix the underlying fundamental problem.

The problematic flow is this: When the form in the modal gets submitted, there's an async request to the create action. When that's successful, the page gets reloaded.

Instead, the proper way to do this would be to send a regular browser request to the create action, and then let the controller handle what happens next (i.e. in this case a redirect to the previous view). This is the standard flow for Rails update actions and it ensures that features like flash notifications work correctly.

To get there, we just need the modal window to have a proper HTML form with a POST action. There's really no reason to do that in JavaScript when the form semantics we need are already completely handled by HTML.
And then it's just a change to the create action that it redirects instead of returning a JSON response.

**Comment by ysbaddaden** [comment]
**Yes!** I can't agree more!

My moto: _if you're writing more JS, then you're probably doing something wrong, especially when doing front <-> back communication_ (tip: try removing some JS instead).

Note that Turbolinks can be used to avoid a full page refresh. We're on Turbolinks 2.5 (aka [turbolinks-classic](https://github.com/turbolinks/turbolinks-classic)) so I'm sure it does work this way, but [Turbolinks 5](https://github.com/turbolinks/turbolinks) is fully integrated with Rails. It can post the form as a XHR request, display a loading bar, deal with the redirection, (Rails sends a special header for Turbolinks to follow, instead of a `Location`), and more.
