### ISSUE TITLE
X is truncated when confirming a sample transfer

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1533]
The last X is visually truncated when confirming a sample transfer.

![image](https://user-images.githubusercontent.com/25181052/158208825-5875b21f-8457-4e5a-82fc-ba87a6305e42.png)

**Comment by straight-shoota** [comment]
No, that's unrelated to #1510. There is enough space in the parent element.
This happens because of a width limitation of the text field. I chose that to match the content width that I'm seeing here (in Firefox):

![grafik](https://user-images.githubusercontent.com/466378/158209636-65f0e12b-b432-4fe4-b459-9a4f28c91935.png)

Apparently, your browser comes to a different conclusion. We can easily make the field larger to accomodate for that. Then there will be some padding on the right sight in some browsers (like mine). That's probably okay. We could invest more into making a perfect fit based on local rendering results, but I fear that would be overkill for this.

**Comment by diegoliberman** [comment]
Let's just do it wider.
