### ISSUE TITLE
QC info is not included in transferred sample

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#1573]
**Found in version:** 42291fa

**Preconditions:**
- There are 3 institutions (`A`, `B`, and `C`).
- `A` has a batch with 3 samples (`s1`, `s2`, `s3`).
- One of them is a QC sample (`s1`).

**Steps to reproduce:**

1. From the institution `A` to `B`, transfer `s2` and `s3`. When transferring them, check `Include a copy of the QC data`.
2. Confirm the samples transfer in institution `B`.
3. Navigate to the samples and observe the information displayed.
4. From the institution `B` to `C`, transfer `s2` and `s3`. Here, the following message is displayed: `There is no Quality Control (QC) info available for these samples.
5. Try to confirm the samples' transfer in Institution `C`.

**Obtained result:**
- The transferred samples cannot be confirmed in the institution `C.`
- When viewing the transferred samples in the institution `B`, the QC info is not displayed.
 

<img width="738" alt="image" src="https://user-images.githubusercontent.com/518152/161119793-7f73ed1b-f15c-49c1-95d2-5b681005e93c.png">

**Comment by ysbaddaden** [comment]
@devduarte The bug is actually two folds:

1. We expected `includes_qc_info` to be `true` but it was `on` (fixed in #1574).

2. We check whether the sample belongs to a batch with a QC sample to display a "There is no Quality Control (QC) info available for these samples" message, but the sample may have already been transferred and thus already has a QC info attached, so we still display the message! It ain't technically wrong (we won't copy anything) but it's still confusing, because the sample does have QC attached.

ping @diegoliberman

**Comment by ysbaddaden** [comment]
@devduarte I moved the issue back to TODO, since we still have the confusing message when trying to transfer samples that already got transferred and already have copied QC info.

**Comment by diegoliberman** [comment]
I would expect not to see the error message, as the Sample does have QC info (a copy of it).  If it's a trivial fix, let's do it now.  If not, let's create a separated ticket, as transferring a 2nd time isn't a usual use case.
