### ISSUE TITLE
Error: Asset names passed to helpers should not include the "/assets/" prefix

### ISSUE THREAD

**Issue by straight-shoota** [instedd/cdx#1645]
I get this error when doing the `bulk_print` action on `/samples` with Rails 5.0.7.2:
```
ActionView::Template::Error (Asset names passed to helpers should not include the "/assets/" prefix. Instead of "/assets/layers.png", use "layers.png"):
    2: %html
    3:   %head
   4:     %title Connected Diagnostics Platform
    5:     = wicked_pdf_stylesheet_link_tag "application", :media => "all"
    6:     = wicked_pdf_stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;700&display=swap"
    7:   %body
    8:     = yield
  app/views/layouts/pdf.html.haml:5:in `_app_views_layouts_pdf_html_haml__2687258733380071559_69820061714700'
  app/controllers/samples_controller.rb:126:in `block in bulk_print'
  app/controllers/samples_controller.rb:125:in `bulk_print'
```

**Comment by diegoliberman** [comment]
It looks related to #1634.

**Comment by straight-shoota** [comment]
It's related in the way that I get this error after fixing #1634. But the cause is entirely different.

**Comment by ysbaddaden** [comment]
It looks like `wicked_pdf_stylesheet_link_tag` generates an invalid link tag, but it's supposed to inline the CSS:
https://github.com/mileszs/wicked_pdf/commit/c8b8afa66c8b4c4e5a35308bd495e7531e5d9416

Or there is something in the SCSS file?

**Comment by ysbaddaden** [comment]
This is a [known issue](https://github.com/mileszs/wicked_pdf/blob/0b6c198383ccd894eafbe022ab6685f425701829/README.md#wicked_pdf-helpers) of `wicked_pdf` with the Rails' asset pipeline.

I have no idea why it only started failing since the Rails 5 upgrade, since it's only affecting the Rails 4.2 fallback version, and Rails 5 is working nicely :shrug: 

I just made a commit that fixes the issue, and should optimize performance a bit, by using a minimal CSS file for printing PDF, instead of the big application CSS.

**Comment by ysbaddaden** [comment]
Damn, now it's the multipage renderer that doesn't work anymore (`samples#bulk_print`) :sob

**Comment by ysbaddaden** [comment]
This is because of `url(//fonts.google.api)` in `variables.scss` that `wkhtmltopdf` fails to interpret when using the base64 encoding... but has no problem when using the regular inline stylesheet... which doesn't work when trying to render a single page :face_exhaling:
