### ISSUE TITLE
[BUG] Timeout when printing box with 108 labels

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1715]
When printing a box labels, you get an error for boxes with 108 samples.  I didn't get an error with a box that has 99 samples.

![image](https://user-images.githubusercontent.com/25181052/173452055-e01fc4f0-5aa1-4f0f-97eb-176547550bd4.png)
![image](https://user-images.githubusercontent.com/25181052/173452144-391282a3-c7c8-4153-8719-1f0dc2e5d47a.png)

![image](https://user-images.githubusercontent.com/25181052/173452001-498677a9-fcb8-4af1-ba28-3d2248f01be0.png)

### Version
Version: dev-01802a4 (build 1580)

**Comment by ysbaddaden** [comment]
We use `wkhtmltopdf` to generate the PDF from HTML pages. I already optimized it to generate the PDF from a single HTML page, instead of 1 HTML per page that was even slower.

A quick workaround could be to increase the timeout on the production servers? What do you think @mati?

We can try some other things in parallel to optimize the generation time:

1. Try to use the SVG generator instead of PNG images, it might have a positive impact?
2. Consider the [prawn](https://prawnpdf.org/api-docs/2.3.0/) gem to generate PDF instead of `wkhtmltopdf`. It requires to rewrite the PDF generation process, and should take 1 (maye 2 days) to implement and some back & forth with the client to test on their printer.

**Comment by straight-shoota** [comment]
108 is the max for purpose box types that are currently implemented.
You can technically create custom boxes with an arbitrary number of samples, but that doesn't seem very practically relevant. We could even put in a limit there.

So increasing the timeout could be a good short term solution. What is the timeout currently?

In general, PDF generation shouldn't take that long. Even though they have many pages, those are quite small and contain few objects. So I think a long-term solution should be optimizing PDF generator performance and IMO there should not be a need for an async job then.

**Comment by matiasgarciaisaia** [comment]
The timeout doesn't come from the Docker image (ie, it's not instedd/nginx-rails).

So it's Rancher's haproxy's timeout.

I've updated that timeout in Staging to 60 seconds - the large PDF doesn't timeout anymore 🎉 

The thing is - we'll have to check this issue in both production environment, since those aren't behind Rancher's proxy. The setting may be different there.

**Comment by ysbaddaden** [comment]
My guess is that the PDF contain lots of PNG images as data-uri attributes, it makes a big HTMl page and it's slow to process. I know that prawn is slow to decode/reencode PNG images. Hence my proposal to try out SVG.

**Comment by diegoliberman** [comment]
All right, I'll test this in Prod once we deploy.

**Comment by diegoliberman** [comment]
Working fine in Prod with 108 samples.
