### ISSUE TITLE
[BUG] When transferring, box ID isn't detected if there is a trailing space at the beginning

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1718]
### Steps to reproduce the error
1. Obtain a valid BOX id from your institution
2. Copy the box ID but with a blank space at the beginning of the string, for instance ` e89222fc-ed39-2544-15d3-10531b8fca22`
3. Try to transfer that box by pasting the ID.  
<img width="653" alt="image" src="https://user-images.githubusercontent.com/25181052/173577941-f2ca7096-1283-4508-8bca-44b331d3339c.png">

4. After pasting the ID, you will get no feedback at all.  So you don't understand what's wrong.

### Expected result
I think we should automatically remove any blank space / line break from the beginning and from the end of the entered value. 

### Note
Bear in mind that it also happens for line breaks:
`
8ecd7efc-e101-47da-1d09-da8c24f78cbd`

Which for some reason you get when copying the ID from the box detail form:
<img width="664" alt="image" src="https://user-images.githubusercontent.com/25181052/173575612-e64f1335-ae71-4ada-9037-3ce80c12b024.png">

But it only happens if you start the selection when the mouse cursor is an arrow.  See video below:

https://user-images.githubusercontent.com/25181052/173577271-0ae1d455-3165-42e0-a744-cbc02e8a8017.mov

### Bonus
Can we do something so that when copying the ID from the box detail form, it doesn't get the line break at the beginning? If it's easy, can we add an icon for copying the ID? Think of this icon/action that we will probably reuse it in many places of the site, perhaps even in multiple fields of the same form

**Comment by straight-shoota** [comment]
Stripping the input should be easy to do.

Regarding the bonus features:

> Can we do something so that when copying the ID from the box detail form, it doesn't get the line break at the beginning? 

The reason for this behaviour that you start the selection outside the value element and thus your selection (though invisible) seems to contain parts of the label element. And there is a line break between them in the generated HTML code. I don't think it would be easy to avoid this line break because we're using HAML.
Even with ugly mode (which doesn't indent the HTML) there is still a line break.

We could inject raw HTML into the HAML template as a workaround. (or switch to ERB entirely 😝)

> If it's easy, can we add an icon for copying the ID?

Yes, that would be easy. I already suggested that for the shortened UUID displays in tables where it would be even more useful.
For reference, I'm using this vanilla JS implementation at shardbox: https://github.com/shardbox/shardbox-web/blob/2fbce5326509819c3606df2ded4753439345929d/app/views/releases/_infobox.html.j2#L7-L37

**Comment by ysbaddaden** [comment]
I got the issue when copying sample ids. That led me to strip the sample ID when manually adding samples to a box. It's easy and it works.

The copy button would be nice, but should probably be a bit everywhere (sample id, batch id, box id, ...) and yes, aside the short uuids.
