### ISSUE TITLE
Move the blind check box to the box detail

### ISSUE THREAD

**Issue by diegoliberman** [instedd/cdx#1769]

**Comment by leandroradusky** [comment]
I've moved the checkbox to the box detail and samples blind correctly. 
**But** from the index we can access box detail ("read only"), there is no edit there to allow unblinding the samples and this is only available after transferring it. Is this an expected behavior? or we should as well allow unblinding samples from the box details form? 
cc @diegoliberman

**Comment by diegoliberman** [comment]
We will allow to edit in #1772, but it isn't a priority right now.  Unless you think it's easy (<8h) and prefer to do it now.

**Comment by ysbaddaden** [comment]
This change means that: the sender no longer blinds all boxes when creating a transfer package, but selectively chooses to blind some boxes when she creates them. Is that the correct behavior?

For the create box part, there should be no issue with permissions: the creator of the box is the owner of the box.

**Comment by diegoliberman** [comment]
This is correct.  In fact, transferring multiple boxes at once, isn't a known use case.  Adding more than 1 box in the transfer was implemented because it added a feature and it was trivial at the time.  If it ever becomes a difficulty, we'll change it so that only 1 box can be transferred at once.
