### ISSUE TITLE
Encounters CRUD

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#261]
An encounter is our equivalent of a Test Order. Review this screens, along with the protocol detail screens for a way to link existent samples into a single encounter.

**Comment by bcardiff** [comment]
pending after review:
- [ ] better patient logic match (now it's by patient_id instead of maybe(entity_id) )
- [ ] style test results assays in table with images
- [ ] force order of test results assays. (seeds?)
- [ ] enforce security policies
- [ ] better style search popup 
- [ ] style institution combo (react way)
- [ ] alignment of components in grid. some have paddings others don't.

- should we have a components page around?

**Comment by bcardiff** [comment]
@mscebba, read comments above for pending styling things that will need your work.

**Comment by mmuller** [comment]
Ok in version 0.11-pre10
