### ISSUE TITLE
Test result detail view

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#344]
A page for details about an individual test result, including all the custom fields reported by that device.

**Comment by bcardiff** [comment]
@nekron there are some issues that needs to be addressed regarding how to know which kind of field is trying to be displayed. Review the [test_results/show.haml](https://github.com/instedd/cdx/blob/master/app/views/test_results/show.haml) and leave comments :-)

Otherwise it's done for the time being

**Comment by bcardiff** [comment]
We won't be doing anything regarding printing the barcode right now. We will wait first for the main use case of printing a bunch of barcodes.

**Comment by mmuller** [comment]
Ok in version 0.6-pre3
