### ISSUE TITLE
[Encounters] quantitative result allows to write letters but then ignores them

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#556]
Expected: forbid the user to write letters in the quantitative result

**Comment by pmallol** [comment]
The user can still write: "e", ".","," and "+"

**Comment by pmallol** [comment]
The user can still write: "e", ".","," and "+"

**Comment by asterite** [comment]
To make this work we need to set lower and upper integer bounds for the values for the quantitative results. We are using an HTML5 number input and it allows those chars to write floats with exponential notation.

**Comment by asterite** [comment]
Now you can't write letters, but you can submit a single "+" or "-", because otherwise there's no way you can start to write negative numbers (or explicitly positive numbers, if you want to do that). In those two particular cases I assume nothing was written and the field will remain empty after hitting "Save".

**Comment by pmallol** [comment]
Ok in Version: 0.7-pre9
