### ISSUE TITLE
[hierorgs] Allow the user to choose to display elements from the current node or to include the elements of the child nodes

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#571]
https://projects.invisionapp.com/d/main#/console/4103589/117714360/preview

Checkbox to include or not the contents of the children nodes.

`<context_uuid>-!` will imply only the current context.
`<context_uuid>-*` will include the content of the children nodes.

**Comment by vtiffenberg** [comment]
Policies do not have scoping at the moment. And since they do not have any column which to identify them as a level or other of the hierarchy, the scoping (and subsequent adaptation to this ticket) are not being done

**Comment by vtiffenberg** [comment]
Styling issues remaining:
- [ ] Enlarge left margin next to checkbox
- [ ] Border colour for checkbox needs to be lightened
- [ ] Highlight selected location (CSS for that trampled by something else)
- [ ] Lines to the left are too short and too thin
- [ ] Line under search is black instead of light gray.

**Comment by nekron** [comment]
Moved remaining issues to #772.

**Comment by mmuller** [comment]
Ok in version 0.11-pre6
