### ISSUE TITLE
Server error when showing 'Test Result' view

### ISSUE THREAD

**Issue by mmuller** [instedd/cdx#643]
Found in version:
0.7-pre10

Preconditions:
There is a Test Result 'Foo'

Reproduce steps:
Go to the Test Results listing
Click on the row of the Test Result 'Foo'

Actual result:
A server error is thrown

Additional information:
The following Test Result was used in this test: http://cdx-stg.instedd.org/test_results/fceb0229-0265-9b2a-e13c-f306fc65a5ac

**Comment by spalladino** [comment]
It was a configuration issue, which was caused by https://github.com/instedd/cdx/commit/27556464608ec3f8be5dadac7e9eb6616c5229c7.

When devise secret key was set to something different than the default value, as that same key was used for encrypting tests' sensitive data, decryption was unsuccessful and caused the 500. The secret key was rolled back to its original value for stg now.

**Comment by mmuller** [comment]
Ok in version 0.7-pre11
