### ISSUE TITLE
Alert messages are not being sent

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#820]
Found in Version: 0.10-pre4

1. Create a new Alert, for example:

> Step 1: select  ‘Device Errors’ category
> Step 2: Enter the ‘ERRORS’ value, values can be an integer such as ‘200’ or a range ‘100-500’
> Step 3: Select ‘record’ field for ‘AGGREGATION TYPE’ drop down.
> Step 4: Select ‘email’ field for CHANNEL
> Step 5: Select an ‘INTERNAL RECIPIENT’ to receive alerts
> Step 6: enter text into the ‘EMAIL MESSAGE’, such as: "Hello mr {lastname}, Your {alertname} occurred".

2. Create a tests to trigger an alert message, such as:

```{
  "event": {
    "result": "MTB DETECTED MEDIUM",
    "assay_name": "MTB-RIF Assay G4_noQC1_2",
    "sample_ID": "100003",
    "system_user": "JaneDoe",
    "device_serial_number": "4444",
    "end_time": "2016-02-18T20:08:41-05:00",
    "start_time": "2016-02-18T18:31:20-05:00",
    "event_id": "76B4AFBA09A143718CED4767ACC4EAE7",
    "test_type": "0",
   "error_code":"201"
  }
}```

3. Verify there are Incidents caused by the uploaded tests under Settings > Incidents
4. Check Alert Messages Sent inside Settings 

Observed:
There are no Alert Messages sent to user configured in alerts

Poirot log:
http://poirot-stg2.instedd.org/activities/2016-02-19/cc027c53-0edc-4113-577e-efb408224f2c

**Comment by anthonyoleary** [comment]
Hi, Did you see any email sent out?  i followed the steps above and could see an email sent locally on my laptop.
I did not put any special Poirot logging into the alert code, I will speak with Mariano about that today.

**Comment by bcardiff** [comment]
Changes were made in d982ff4 to allow cdx-dev to send mails.  Due to default alert_from_email the emails where rejected. Now the alert_from_email is the app_from_email unless ALERT_MAILER_SENDER env variable is set.

Some links fixing and polishing was done in 2e97b5b.

Despite that, the error exhibit in this issue seem to be related to a error in data. The lack of trace prevent to fully diagnose. Probably a email is sent to a sms recipient (empty email address). This should be addressed, but also the notification should be isolated `begin/rescue` in a recipient basis (see: alert_email_inform_recipient and alert_sms_inform_recipient)

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre6
