### ISSUE TITLE
Manufacturer account is able to see Patients and Tests tabs

### ISSUE THREAD

**Issue by cisaacs01** [instedd/cdx#872]
![man1](https://cloud.githubusercontent.com/assets/2486669/13223137/ea35d7a4-d97a-11e5-9d3d-212b52fb0322.jpg)
![man2](https://cloud.githubusercontent.com/assets/2486669/13223142/ef258002-d97a-11e5-9ac1-0b2da5937fb1.jpg)

**Comment by nekron** [comment]
You have more than one institution created there, and I'm assuming that they're of different types. That's why you are seeing the whole navigation. If you create only a manufacturer institution, you would only see the things that regards to those kind of organisation.

A different thing would be to scope the top navigation to the selected context, which is not being done right now.
