### ISSUE TITLE
Allow manual entry of Sample IDs

### ISSUE THREAD

**Issue by nditada** [instedd/cdx#937]
In the Site settings, add a "Allow manual entry" checkbox under "Sample ID reset policy". If the Site has set that option to true, the system will still suggest the next number for the sample ID, but the user will be able to edit it.

Validation that the entered number is still unique within the selected period for "Sample ID reset policy" should still be made.

**Comment by bcardiff** [comment]
What should happend if
* two users manually enters the same sample id before saving the test order? For sure the first should win.
But then,
* If the users close/leave the test order creation page he/she will be unable to enter the sample id as fresh. And will need to input it as an existing sample. 

So there is a chance that the system will end with potentially orphans and empty samples.

Right now we only have a next_sample_id per site stored and samples are created if and only if a test order is created.

**Comment by cisaacs01** [comment]
Brian raises a good point in relation to the editing of suggested sample IDs. The introduction of CDx where users MUST utilize the sample numbering system is far from ideal. Many have invested in automated barcode systems for example and must be able to use their existing investments. 

For those with such systems we need to be able to support the sample IDs generated by them. Suggestion would be to adopt an all or nothing approach rather than a hybrid. This should be configurable at a site level by the admin user to use either:

Option 1 - Sample IDs generated by CDx
Option 2 - Sample IDs generated by existing methods

If option 2 is selected then no suggested sample ID should be displayed.

For sample IDs generated by existing methods we will need to trust that the system accommodates any duplicates etc.

**Comment by nditada** [comment]
Not suggesting the next ID will not prevent having two users enter the same number. Are you suggesting that if two users type the same Sample ID, we assume their test orders to refer to the same sample?

**Comment by cisaacs01** [comment]
If manual sample ID system is used we should validate against patient name and sample type (#940) for uniqueness. If all parameters match then assume test order refers to same sample. If no match then flag that user ID has been used been used already.

**Comment by nditada** [comment]
Per conversation with Chris:
 [ ] Support manual entry
 [ ] Do not show autonumbers if that's selected
 [ ] Validate that manual sample IDs that are repeated, belong to test orders for the same Patient and Sample Type
 [ ] Display a simple error message with "This sample ID has already been used for another Patient"

**Comment by nditada** [comment]
Do not do if estimate > 8 hours.

**Comment by vtiffenberg** [comment]
- [ ] Support manual entry
- [ ] Do not show autonumbers if that's selected
- [ ] Validate that manual sample IDs that are repeated, belong to test orders for the same Patient and Sample Type
- [ ] Display a simple error message with "This sample ID has already been used for another Patient"

**Comment by nekron** [comment]
We are not currently allowing the user to enter the sample "type".

Let's keep the validation to the same patient and we'll extend it to the type as soon as we have it.

**Comment by mmuller** [comment]
Ok in version 0.12-pre2
