### ISSUE TITLE
Support FTP uploads of zip files from AlereQ

### ISSUE THREAD

**Issue by nditada** [instedd/cdx#982]

**Comment by nditada** [comment]
@cisaacs01 this will be a sizable effort, around 15% of what we have left for the MVP. I guess there's no way around this, right?

**Comment by nekron** [comment]
And Alere PIMA also, isn't it?

**Comment by cisaacs01** [comment]
No, PIMA just sends CSV files when transmitting data through the modem.

**Comment by nditada** [comment]
@cisaacs01  I know you already clarified this but your original email with Alere outputs contained plain CSVs for AlereQ and a zip file for Alere PIMA. That's the reverse of what you are stating here. Can you confirm that was just because you manually manipulated the results, decompressed the AlereQ results and compressed the Alere PIMA?

In other words, can you confirm (again) that: AlereQ uploads zip files. Alere PIMA uploads CSV files.

**Comment by cisaacs01** [comment]
I recall some manual manipulation of files as I had difficulty attempting to upload to GitHub.

Alere-q = .zip format
Alere Pima = .csv format.

I will provide exact files via FTP server when I get home for evidence.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by cisaacs01** [comment]
I have uploaded a number of Alere files to a FTP server. The credentials are:

Host:                     dbhost01.bluefrontier.co.uk
User:                     find_ftp
Password:           nes_ufEX2$3t

Note that the Alere devices MUST upload their files to a specific named root folder, respectively PIMA-EXPORT and ALEREQ-EXPORT. The devices will fail to upload results if these folders do not exist on the FTP server.

Another consideration is what to do with parsed files. As they are processed it is ideal that they are moved to another folder so that the CDx doesn’t have to keep trawling through files that have already been done. It is also ideal that bad files are moved to a separate folder if they cannot be parsed so as not to end up with the main folder full of junk.

**Comment by cisaacs01** [comment]
I have uploaded a number of Alere files to a FTP server. The credentials are:

Host:                     dbhost01.bluefrontier.co.uk
User:                     find_ftp
Password:           nes_ufEX2$3t

Note that the Alere devices MUST upload their files to a specific named root folder, respectively PIMA-EXPORT and ALEREQ-EXPORT. The devices will fail to upload results if these folders do not exist on the FTP server.

Another consideration is what to do with parsed files. As they are processed it is ideal that they are moved to another folder so that the CDx doesn’t have to keep trawling through files that have already been done. It is also ideal that bad files are moved to a separate folder if they cannot be parsed so as not to end up with the main folder full of junk.

**Comment by nekron** [comment]
Our policy was not to move any files as we didn't expect to have a dedicated ftp server only for cdx. We were expecting cdx to connect to an already existing ftp server, a working part of the site's workflow, and our idea was to have as least impact in that server as possible.

Nevertheless we are keeping a local record of the files we process to avoid duplicated tests and unnecessary processing.

**Comment by mmuller** [comment]
Ok in version 0.11-pre13
