### ISSUE TITLE
Custom roles for either admin or reader not working

### ISSUE THREAD

**Issue by pmallol** [instedd/cdx#995]
Found in Version: 0.11-pre10

As Institution Admin:
1. Navigate to 'Roles' under Settings
2. Click on button to create new reader Role:
3. In Policy select 'Institution' as Type, and 'Reader' as Action
4. Navigate to 'Users' and create a new user 'Foo' assigning the reader Role

As Reader user 'Foo':
1. Open CDx 

Obtained:
The user 'Foo' cannot access to any data belonging to the Institution.

Expected:
User 'Foo' should be able to read information for the Institution its role belongs to.

**Comment by bcardiff** [comment]
@nekron what should happen with a user that has only a Reader policy of an institution?

User is unable to access because `after_sign_in_path_for` is unable to determine a path to show. It returns `nil` and lead to `/users/:id` by default, which correctly does not exist, but triggers the error exhibited. There is no screen that shows data only for an institution reader, for example dashboard_path requires access to TestResult, otherwise empty data will be shown.

A Institution reader is a needed policy but not enough to interact with the system. I rather add an empty page as default `after_sign_in_path_for` that loads the side bar tree with some message about "You don't have enough permissions to view further information"

**Comment by nekron** [comment]
Read only on an institution at least should enable it to be displayed in the side navigation. Regardless of the other related permissions.

The issue was originally triggered when the user had access to admin the patients of an institution. But the institution was never displayed in the side navigation.

Going to the patients didn't enabled the creation link because the context could never be selected.

**Comment by bcardiff** [comment]
Well, that would be that there are some functional dependency between the policies. But, for the "just read institution" policy, what content should be displayed on the main area?

**Comment by mmuller** [comment]
Ok in version 0.11-pre12
